version : 0.1
runtime : java8
collections:
    - id: templates
      title: Templates
      description: Quick starts
       
    - id: tutorials
      title: Tutorials
      description: Popular Java tutorials

    - id: algorithms
      title: Algorithms
      description: Popular algorithms in Java 
