version : 0.1
runtime : java8
collections:
    - id: templates
      title: Templates
      description: Quickstart templates
       
    - id: tutorials
      title: Tutorials
      description: The practical guides for programmers

    - id: algorithms
      title: Algorithms
      description: The most popular algorithms and data structures

    - id: interviews
      title: Interviews
      description: Code interviewed from well known companies

    - id: practices
      title: Practices
      description: Challenge yourself and fine tune yours skills
